export type ApiErrorCode =
  // Auth
  | 'AUTH_EMAIL_ALREADY_REGISTERED'
  | 'AUTH_GOOGLE_ACCOUNT_NOT_FOUND'
  | 'AUTH_CODE_INVALID'
  | 'AUTH_CODE_ALREADY_USED'
  | 'AUTH_CODE_EXPIRED'
  | 'AUTH_ACCOUNT_ALREADY_VERIFIED'
  // Usuario
  | 'USER_PASSWORD_INCORRECT'
  | 'USER_PASSWORD_SAME'
  | 'USER_PROFILE_NOT_FOUND'
  | 'USER_ADDRESS_NOT_FOUND'
  | 'USER_ADDRESS_LIMIT'
  | 'USER_ADDRESS_DEFAULT_DELETE'
  // Tienda
  | 'STORE_ACCESS_DENIED'
  | 'STORE_ADMIN_REQUIRED'
  | 'STORE_INSUFFICIENT_PERMISSIONS'
  | 'STORE_ALREADY_MEMBER'
  | 'STORE_LAST_OWNER'
  | 'STORE_LAST_OWNER_LEAVE'
  | 'STORE_ROLE_SELF_CHANGE'
  | 'STORE_STAFF_CANNOT_REMOVE'
  | 'STORE_MANAGER_REMOVE_RESTRICTED'
  // Producto
  | 'PRODUCT_NOT_FOUND'
  | 'PRODUCT_SKU_DUPLICATE'
  | 'PRODUCT_LINE_BRAND_MISMATCH'
  | 'PRODUCT_COMPARE_PRICE_INVALID'
  | 'PRODUCT_ALREADY_ACTIVE'
  | 'PRODUCT_ALREADY_INACTIVE'
  | 'PRODUCT_NOT_DRAFT'
  | 'PRODUCT_OUT_OF_STOCK'
  | 'PRODUCT_NO_VARIANTS'
  | 'PRODUCT_NO_IMAGES'
  | 'PRODUCT_NO_STOCK_IN_VARIANTS'
  | 'PRODUCT_DELETE_REQUIRES_DRAFT'
  | 'PRODUCT_LAST_VARIANT'
  | 'PRODUCT_USE_PUBLISH_ENDPOINT'
  | 'PRODUCT_CATALOG_ADMIN_REQUIRED'
  | 'PRODUCT_ATTRIBUTE_ALREADY_LINKED'
  | 'PRODUCT_ATTRIBUTE_VALUE_NOT_FOUND'
  // Imágenes
  | 'PRODUCT_IMAGE_EMPTY'
  | 'PRODUCT_IMAGE_TOO_LARGE'
  | 'PRODUCT_IMAGE_FORMAT_INVALID'
  | 'PRODUCT_IMAGE_CONTENT_MISMATCH'
  | 'PRODUCT_IMAGE_WRONG_PRODUCT'
  // Inventario
  | 'INVENTORY_QUANTITY_ZERO'
  | 'INVENTORY_INSUFFICIENT_STOCK'
  | 'INVENTORY_NEGATIVE_ONLY_ADJUSTMENT'
  | 'INVENTORY_SALE_INTERNAL_ONLY'
  | 'INVENTORY_ACCESS_DENIED'
  // Carrito
  | 'CART_NOT_FOUND'
  | 'CART_ITEM_NOT_FOUND'
  | 'CART_VARIANT_NOT_FOUND'
  | 'CART_ITEMS_EMPTY'
  | 'CART_ACCESS_DENIED'
  // Orden
  | 'ORDER_CART_NOT_FOUND'
  | 'ORDER_CART_EMPTY'
  | 'ORDER_ADDRESS_STORE_MISMATCH'
  | 'ORDER_INSUFFICIENT_STOCK'
  | 'ORDER_CUSTOMER_ROLE_REQUIRED'
  | 'ORDER_BUYER_PHONE_REQUIRED'
  // Order Group
  | 'ORDER_GROUP_NOT_FOUND'
  | 'ORDER_GROUP_INVALID_STATUS'
  // Pagos
  | 'PAYMENT_ORDER_NOT_FOUND'
  | 'PAYMENT_RECORD_NOT_FOUND'
  | 'PAYMENT_ORDER_NOT_PENDING'
  | 'PAYMENT_METHOD_MISMATCH'
  | 'PAYMENT_ACCESS_DENIED'
  // Cupones
  | 'COUPON_CODE_DUPLICATE'
  | 'COUPON_DATE_INVALID'
  | 'COUPON_NOT_FOUND'
  | 'COUPON_INVALID'
  | 'COUPON_ACCESS_DENIED'
  // Devoluciones
  | 'RETURN_NOT_FOUND'
  | 'RETURN_ORDER_NOT_FOUND'
  | 'RETURN_ORDER_NOT_DELIVERED'
  | 'RETURN_ORDER_NOT_YOURS'
  | 'RETURN_NOT_YOURS'
  | 'RETURN_DUPLICATE'
  | 'RETURN_ITEM_NOT_FOUND'
  | 'RETURN_ITEM_QUANTITY_EXCEEDED'
  | 'RETURN_NOT_PENDING'
  | 'RETURN_NOT_APPROVED'
  | 'RETURN_ACCESS_DENIED'
  // Reseñas
  | 'REVIEW_NOT_FOUND'
  | 'REVIEW_DUPLICATE'
  | 'REVIEW_NOT_YOURS'
  | 'REVIEW_APPROVED_DELETE_DENIED'
  | 'REVIEW_NOT_PENDING'
  | 'REVIEW_ACCESS_DENIED'
  // Wishlist
  | 'WISHLIST_PRODUCT_NOT_FOUND'
  | 'WISHLIST_ITEM_DUPLICATE'
  | 'WISHLIST_LIMIT_EXCEEDED'
  // Genéricos
  | 'VALIDATION_ERROR'
  | 'DATA_INTEGRITY_VIOLATION'
  | 'INTERNAL_ERROR';

export interface ApiErrorResponse {
  code: ApiErrorCode;
  error: string;
}

/** Extrae el code del body de un error HTTP. */
export function apiCode(err: unknown): ApiErrorCode | null {
  return (err as any)?.error?.code ?? null;
}

/** Extrae el mensaje legible del body de un error HTTP. */
export function apiMessage(err: unknown, fallback = 'Error inesperado.'): string {
  const body = (err as any)?.error;
  return body?.error ?? body?.message ?? fallback;
}
